name: eclub
description: "Look and feel personalizado en Flutter para eCLUB Paraguay 2025, navegación y diseño basado en Figma."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  fl_chart: ^0.66.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/analysis/